version: "2"
checks:
  method-lines:
    config:
      threshold: 50

engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60

exclude_patterns:
  - "**/test/*"
  - "**/*.min.js"
  - "**/*.bundle.js/*"
