name: francy
version: "2.0.2"
license: "MIT"
date: 2023-01-25
description: |
    Framework for Interactive Discrete Mathematics

authors:
    - name: Manuel Martins
      url: http://github.com/mcmartins

maintainers:
    - name: Manuel Martins
      url: http://github.com/mcmartins

GAP: ">=4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.6.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "json"
      version: ">= 2.0.0"
      url: "https://gap-packages.github.io/json/"
    - name: "uuid"
      version: ">= 0.7"
      url: "https://gap-packages.github.io/uuid/"
    - name: "JupyterKernel"
      version: ">= 1.4.1"
      url: "https://gap-packages.github.io/JupyterKernel/"

www: https://gap-packages.github.io/francy
readme: README.md
packageinfo: https://gap-packages.github.io/francy/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/francy/releases/download/v2.0.2/francy-2.0.2.tar.gz

abstract: |
    The <span class="pkgname">Francy</span> package allows to use graphics in GAP.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    Jupyter, User Interface, Interactive, Graphics, Charts, Graphs.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Mar23</span>]   <b class='BibAuthor'>Martins, M.</b>,
     <i class='BibTitle'>francy, Framework for Interactive Discrete Mathematics,
             Version 2.0.2</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/francy">https://gap-packages.github.io/francy</a></span>.
    </p>
    

bibtex: |
    @misc{ francy2.0.2,
      author =           {Martins, M.},
      title =            {{francy},    Framework    for   Interactive   Discrete
                          Mathematics, {V}ersion 2.0.2},
      month =            {Jan},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/francy}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{francy}}},
      keywords =         {Jupyter;   User   Interface;   Interactive;  Graphics;
                          Charts; Graphs},
      printedkey =       {Mar23}
    }

